### ISSUE TITLE
.net SDK ERROR.

### ISSUE THREAD

**Issue by LatusPL** [Kaydax/flp2midi#10]
Hello, i have an problem converting flp files into mid. there isn't application in there but batch file worked instad although it gave me this weird ERROR: 

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'publish' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
Archiving...
'7z' is not recognized as an internal or external command,
operable program or batch file.

It also repeat that over and over again until it stops with press any key rather than spaming the error. Is enyone having the same problem as me? And did someone fixed it? Does it require some .net SDK extentions and 7Zip?

**Comment by LatusPL** [comment]
Im trying to download 7zip now.

**Comment by LatusPL** [comment]
i've got another error with the zip but its diffrent:

'7z' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Kaydax** [comment]
you downloaded the source code and not the application itself, then tried to build it without a valid .net sdk
