### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by CalypsoTH** [Kaydax/flp2midi#11]
So I am confused on the linux version, I turned it into a sh and it says
Usage: flp2midi.exe path to flp file 
List of current console vars:
-fc | --force-color > Makes all notes map to the color they are mapped to in the pattern than what the MIDI Out channel is set to
-de | --disable-echo > Disables the generation of echo notes if echo is enabled on the channel
Press any key to exit... 

Do I like put the file in a folder then use one of the commands or something?

**Comment by Kaydax** [comment]
the linux version doesn't have to be turned into a .sh file as its a linux binary, not bash code. Secondly the usage tells you exactly how to use it, example: `./flp2midi /home/username/song.flp`

**Comment by CalypsoTH** [comment]
> the linux version doesn't have to be turned into a .sh file as its a linux binary, not bash code. Secondly the usage tells you exactly how to use it, example: `./flp2midi /home/username/song.flp`

So I did type in ./flp2midi /home/(my username)/(name of the flp).flp after turning the file back to a regular file but what else do i do? Do i type in -fc or something after I do it because when i try to it doesn't work because of the press any key to exit. Is there something I'm doing wrong?

**Comment by CalypsoTH** [comment]
wait hold on

**Comment by CalypsoTH** [comment]
Alright thanks for helping out on discord
