### ISSUE TITLE
I dont understand how this software works

### ISSUE THREAD

**Issue by electrotrent** [Kaydax/flp2midi#14]
1. it wants to make changes to my computer (kinda normal)
2. it automatically downloaded software to open the file that seemed to be a normal file (big red flag)
3. upon opening, it opened the PC's console (gigantic red flag)
4. at that point, I tried to get rid of it but there was no uninstallation file for whatever it downloaded (once again a giant red flag)
5. I tried to find the file but I couldn't find it, as well as the fact that all of the files on my computer started flashing for a second after being installed

**Comment by Kaydax** [comment]
Its completely open source, if you don't trust my release compile it yourself. Also:
1. No shit, it reads a FLP and outputs a midi file
2. What do you mean by this? It installs nothing to your PC or downloads anything
3. Its a console application, it does not have a GUI and just opening the exe does nothing, read the readme
4. Its a portable application, it again doesn't install anything or itself
5. What?

**Comment by Kaydax** [comment]
Also changed the issue title because again, the software isn't suspicious and you obviously don't understand how it works
