### ISSUE TITLE
Im dumb

### ISSUE THREAD

**Issue by nikcoliolol** [Kaydax/flp2midi#16]
I dont get it, what kind of exe is it that i have to open? do i have to like, compile it? If so, **hOw**

**Comment by Kaydax** [comment]
You download the program for your operating system, extract the archive to a folder, and then just drag and drop your flp project file onto the exe inside of the folder. Else you can use the command prompt in the folder and run the program by doing `flp2midi.exe <path to file>`

**Comment by nikcoliolol** [comment]
> You download the program for your operating system, extract the archive to a folder, and then just drag and drop your flp project file onto the exe inside of the folder. Else you can use the command prompt in the folder and run the program by doing `flp2midi.exe <path to file>`


theres a problem tho, the command prompt chrashes when i open it and press a random key, how can i fix it?
Also maybe i can add you on discord if you dont understand whats happening, my name is King Jammer#0414 
maybe we can talk about it there

**Comment by Kaydax** [comment]
Solved - Downloaded the source code and not the release and was trying to build it without any sdk installed. Same as issue #10
