### ISSUE TITLE
midi notes with the same channel color get exported as one track only instead of separate tracks according to patterns

### ISSUE THREAD

**Issue by Spherey** [Kaydax/flp2midi#17]
if the midi notes in 2 or more separate patterns happen to have the same channel color, they get mixed down into one track when using -fc rather than being separated according to pattern separation which causes note interference (e.g. note arts muting the main melody because it's spammy and since it's on the same track it mutes the previous note)

**Comment by Kaydax** [comment]
This is an intended feature, as flp2midi only exports patterns to separate tracks when the patterns are on separate tracks in the playlist itself, not based on the pattern
