### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kayky21** [Kaydax/flp2midi#18]
![image](https://user-images.githubusercontent.com/127033973/222966407-f3868459-8d20-44e6-9f93-625c65c9b2c7.png)

**Comment by Kaydax** [comment]
What version of fl studio are you using

**Comment by kayky21** [comment]
> What version of fl studio are you using

i have no idea,im just trying to load this file
![image](https://user-images.githubusercontent.com/127033973/222999418-43c15002-75fd-4b59-a5e3-228c4abb4b31.png)

**Comment by Kaydax** [comment]
That doesn't help me at all know what the issue is. I need to know what version of fl studio the project file was made with. If anything add me on discord and send me the file

**Comment by kayky21** [comment]
nevermind then, it aint important anyways, i was just going to try and use it to improve a chart im making for the song

but if you still want to take a look at it, heres the [g-drive link](https://drive.google.com/drive/folders/1Pz1ntqQHZbk0ljwQO4_e310NxXB-Iotx)
the flp is inside the "GameBreaker_NAYU MIX" zip

srry for the waste of time i guess

**Comment by Kaydax** [comment]
This flp file is way to modern for what current flp2midi supports, on top of the fact its way to complex as well, as it uses paid vsts and the Sampler VST with patterns attached which is very untested. If anything you are going to have to manually clean up the flp yourself and make it work using the MIDIOut VST. Also flp2midi is way too over engineered for even doing this and your best option is to just export from fl studio itself
