### ISSUE TITLE
i have a problem with the build.bat

### ISSUE THREAD

**Issue by FlakyMC** [Kaydax/flp2midi#2]
hello, i new in this things xd, and i have a problem when i open the build.bat
this are the error messages:
-fatal: not a git repository (or any of the parent directories): .git
-"dotnet" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
-"7z" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
(is in spanish because i talk spanish xd)

**Comment by Kaydax** [comment]
Exact issues in order:
- You didn't clone the repo using git
- You don't have the .net 5/6 sdk installed
- You don't have 7zip installed

**Comment by Kaydax** [comment]
Since there hasn't been a reply I'm closing this ticket
