### ISSUE TITLE
I have a small question about using this tool on mobile

### ISSUE THREAD

**Issue by TheMightyArie** [Kaydax/flp2midi#27]
I heard it's possible to use this tool on a phone. So I decided to run this tool on a mobile linux terminal emulator called Termux. If I install a proot to Termux then a Linux, will it work?

**Comment by Kaydax** [comment]
I remember it working once, but I tried recently and it wasn't working. You may need root but if you get it working let me know

**Comment by TheMightyArie** [comment]
I think I gonna give up since idk how to run Linux apps on Termux.
