### ISSUE TITLE
What do I even do

### ISSUE THREAD

**Issue by PhotonFrog** [Kaydax/flp2midi#7]
I got the Zip downloaded now what I am not good a this whole zip stuff

**Comment by amill1226** [comment]
Mainly confused about the 'First download the release archive and extract it to where ever you want' Step

**Comment by Kaydax** [comment]
Just extract the zip file? Idk how to explain how to extract a zip

**Comment by amill1226** [comment]
I did

**Comment by amill1226** [comment]
But now what it's now a folder

**Comment by Kaydax** [comment]
Open the folder

**Comment by amill1226** [comment]
Open it and do what

**Comment by Kaydax** [comment]
If you don't understand how to read the readme that tells you what to do, then I don't know how to help you

**Comment by amill1226** [comment]
WHat do I open it in

**Comment by Kaydax** [comment]
Please keep issues to actual errors you have with the program itself. If you need general help add me on discord: Kaydax#5987

**Comment by amill1226** [comment]
Sorry
